/**
 * Fuxion Server
 * REST API Server of Fuxion
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost model module.
 * @module model/BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost
 * @version 0.1.0
 */
class BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost {
    /**
     * Constructs a new <code>BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost</code>.
     * @alias module:model/BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost
     * @param idToken {String} 
     */
    constructor(idToken) { 
        
        BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost.initialize(this, idToken);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, idToken) { 
        obj['id_token'] = idToken;
    }

    /**
     * Constructs a <code>BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost} obj Optional instance to populate.
     * @return {module:model/BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost} The populated <code>BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost();

            if (data.hasOwnProperty('id_token')) {
                obj['id_token'] = ApiClient.convertToType(data['id_token'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['id_token'] && !(typeof data['id_token'] === 'string' || data['id_token'] instanceof String)) {
            throw new Error("Expected the field `id_token` to be a primitive type in the JSON string but got " + data['id_token']);
        }

        return true;
    }


}

BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost.RequiredProperties = ["id_token"];

/**
 * @member {String} id_token
 */
BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost.prototype['id_token'] = undefined;






export default BodyOauthGoogleJwtTokenLoginAuthGoogleTokenLoginPost;

