/**
 * Fuxion Server
 * REST API Server of Fuxion
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The OAuth2AuthorizeResponse model module.
 * @module model/OAuth2AuthorizeResponse
 * @version 0.1.0
 */
class OAuth2AuthorizeResponse {
    /**
     * Constructs a new <code>OAuth2AuthorizeResponse</code>.
     * @alias module:model/OAuth2AuthorizeResponse
     * @param authorizationUrl {String} 
     */
    constructor(authorizationUrl) { 
        
        OAuth2AuthorizeResponse.initialize(this, authorizationUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, authorizationUrl) { 
        obj['authorization_url'] = authorizationUrl;
    }

    /**
     * Constructs a <code>OAuth2AuthorizeResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/OAuth2AuthorizeResponse} obj Optional instance to populate.
     * @return {module:model/OAuth2AuthorizeResponse} The populated <code>OAuth2AuthorizeResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OAuth2AuthorizeResponse();

            if (data.hasOwnProperty('authorization_url')) {
                obj['authorization_url'] = ApiClient.convertToType(data['authorization_url'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>OAuth2AuthorizeResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>OAuth2AuthorizeResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of OAuth2AuthorizeResponse.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['authorization_url'] && !(typeof data['authorization_url'] === 'string' || data['authorization_url'] instanceof String)) {
            throw new Error("Expected the field `authorization_url` to be a primitive type in the JSON string but got " + data['authorization_url']);
        }

        return true;
    }


}

OAuth2AuthorizeResponse.RequiredProperties = ["authorization_url"];

/**
 * @member {String} authorization_url
 */
OAuth2AuthorizeResponse.prototype['authorization_url'] = undefined;






export default OAuth2AuthorizeResponse;

