/**
 * Fuxion Server
 * REST API Server of Fuxion
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Transaction model module.
 * @module model/Transaction
 * @version 0.1.0
 */
class Transaction {
    /**
     * Constructs a new <code>Transaction</code>.
     * @alias module:model/Transaction
     * @param amount {Number} 
     * @param concept {String} 
     * @param timestamp {Date} 
     */
    constructor(amount, concept, timestamp) { 
        
        Transaction.initialize(this, amount, concept, timestamp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, amount, concept, timestamp) { 
        obj['amount'] = amount;
        obj['concept'] = concept;
        obj['timestamp'] = timestamp;
        obj['description'] = '';
    }

    /**
     * Constructs a <code>Transaction</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Transaction} obj Optional instance to populate.
     * @return {module:model/Transaction} The populated <code>Transaction</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Transaction();

            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
            }
            if (data.hasOwnProperty('concept')) {
                obj['concept'] = ApiClient.convertToType(data['concept'], 'String');
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], 'Date');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('remaining_balance')) {
                obj['remaining_balance'] = ApiClient.convertToType(data['remaining_balance'], 'Number');
            }
            if (data.hasOwnProperty('reference')) {
                obj['reference'] = ApiClient.convertToType(data['reference'], 'String');
            }
            if (data.hasOwnProperty('category')) {
                obj['category'] = ApiClient.convertToType(data['category'], 'String');
            }
            if (data.hasOwnProperty('subcategory')) {
                obj['subcategory'] = ApiClient.convertToType(data['subcategory'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Transaction</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Transaction</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Transaction.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['concept'] && !(typeof data['concept'] === 'string' || data['concept'] instanceof String)) {
            throw new Error("Expected the field `concept` to be a primitive type in the JSON string but got " + data['concept']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['reference'] && !(typeof data['reference'] === 'string' || data['reference'] instanceof String)) {
            throw new Error("Expected the field `reference` to be a primitive type in the JSON string but got " + data['reference']);
        }
        // ensure the json data is a string
        if (data['category'] && !(typeof data['category'] === 'string' || data['category'] instanceof String)) {
            throw new Error("Expected the field `category` to be a primitive type in the JSON string but got " + data['category']);
        }
        // ensure the json data is a string
        if (data['subcategory'] && !(typeof data['subcategory'] === 'string' || data['subcategory'] instanceof String)) {
            throw new Error("Expected the field `subcategory` to be a primitive type in the JSON string but got " + data['subcategory']);
        }

        return true;
    }


}

Transaction.RequiredProperties = ["amount", "concept", "timestamp"];

/**
 * @member {Number} amount
 */
Transaction.prototype['amount'] = undefined;

/**
 * @member {String} concept
 */
Transaction.prototype['concept'] = undefined;

/**
 * @member {Date} timestamp
 */
Transaction.prototype['timestamp'] = undefined;

/**
 * @member {String} description
 * @default ''
 */
Transaction.prototype['description'] = '';

/**
 * @member {Number} remaining_balance
 */
Transaction.prototype['remaining_balance'] = undefined;

/**
 * @member {String} reference
 */
Transaction.prototype['reference'] = undefined;

/**
 * @member {String} category
 */
Transaction.prototype['category'] = undefined;

/**
 * @member {String} subcategory
 */
Transaction.prototype['subcategory'] = undefined;






export default Transaction;

