/**
 * Fuxion Server
 * REST API Server of Fuxion
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FuxionServer);
  }
}(this, function(expect, FuxionServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FuxionServer.TransactionCreateSchema();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionCreateSchema', function() {
    it('should create an instance of TransactionCreateSchema', function() {
      // uncomment below and update the code to test TransactionCreateSchema
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be.a(FuxionServer.TransactionCreateSchema);
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property concept (base name: "concept")', function() {
      // uncomment below and update the code to test the property concept
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property timestamp (base name: "timestamp")', function() {
      // uncomment below and update the code to test the property timestamp
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property remainingBalance (base name: "remaining_balance")', function() {
      // uncomment below and update the code to test the property remainingBalance
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property reference (base name: "reference")', function() {
      // uncomment below and update the code to test the property reference
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property category (base name: "category")', function() {
      // uncomment below and update the code to test the property category
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property subcategory (base name: "subcategory")', function() {
      // uncomment below and update the code to test the property subcategory
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

    it('should have the property accountId (base name: "account_id")', function() {
      // uncomment below and update the code to test the property accountId
      //var instance = new FuxionServer.TransactionCreateSchema();
      //expect(instance).to.be();
    });

  });

}));
