/**
 * Fuxion Server
 * REST API Server of Fuxion
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FuxionServer);
  }
}(this, function(expect, FuxionServer) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FuxionServer.TransactionsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TransactionsApi', function() {
    describe('restCreateTransactionApiTransactionsPost', function() {
      it('should call restCreateTransactionApiTransactionsPost successfully', function(done) {
        //uncomment below and update the code to test restCreateTransactionApiTransactionsPost
        //instance.restCreateTransactionApiTransactionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restReadItemsApiTransactionsGet', function() {
      it('should call restReadItemsApiTransactionsGet successfully', function(done) {
        //uncomment below and update the code to test restReadItemsApiTransactionsGet
        //instance.restReadItemsApiTransactionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('restReadNeedApiTransactionsTransactionIdGet', function() {
      it('should call restReadNeedApiTransactionsTransactionIdGet successfully', function(done) {
        //uncomment below and update the code to test restReadNeedApiTransactionsTransactionIdGet
        //instance.restReadNeedApiTransactionsTransactionIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
